{"name": "remove_ingredient() - удаление ингредиента: неправильный индекс", "status": "broken", "statusDetails": {"message": "IndexError: list assignment index out of range", "trace": "self = <test_burger.TestBurger object at 0x000001EFD270A4E0>, mock_sauce = <Mock id='2129547987088'>\nmock_filling = <Mock id='2129548163264'>\n\n    @allure.title('remove_ingredient() - удаление ингредиента: неправильный индекс')\n    @allure.description('Проверяем, что программа не сломалась и в списке осталось 2 ингредиента')\n    def test_remove_ingredient_invalid_index_no_changes(self, mock_sauce, mock_filling):\n        # создаем бургер и 2 ингредиента и добавляем их (с индексами 0 и 1)\n        burger = Burger()\n        burger.add_ingredient(mock_sauce)\n        burger.add_ingredient(mock_filling)\n        # пытаемся удалить ингредиент с индексом 2\n>       burger.remove_ingredient(2)\n\ntests\\test_burger.py:184: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <burger.Burger object at 0x000001EFD2F60D70>, index = 2\n\n    def remove_ingredient(self, index: int):\n>       del self.ingredients[index]\nE       IndexError: list assignment index out of range\n\nburger.py:26: IndexError"}, "description": "Проверяем, что программа не сломалась и в списке осталось 2 ингредиента", "start": 1704819163927, "stop": 1704819163928, "uuid": "5eed7e09-e790-479f-a43f-04be132c0fcf", "historyId": "471c6da4a1ac45e23bed04c5ee4e8528", "testCaseId": "471c6da4a1ac45e23bed04c5ee4e8528", "fullName": "tests.test_burger.TestBurger#test_remove_ingredient_invalid_index_no_changes", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_burger"}, {"name": "subSuite", "value": "TestBurger"}, {"name": "host", "value": "DESKTOP-0A7KFK3"}, {"name": "thread", "value": "6484-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_burger"}]}